### ISSUE TITLE
我的工作区似乎无法使用claude

### ISSUE THREAD

**Issue by NoahAmethyst** [bincooo/claude-api#12]
<img width="1097" alt="image" src="https://github.com/bincooo/claude-api/assets/46391031/28a267cf-2190-44ed-b837-2dece65dd2a6">
尝试在dm与channel里与claude交互，但是都没有收到响应，是因为我有什么配置没有做吗
<img width="723" alt="image" src="https://github.com/bincooo/claude-api/assets/46391031/a8182fd0-cf2c-4452-bc21-ee793ca7ad28">

**Comment by bincooo** [comment]
新的工作区现在被限制了，只能开启pro试用才能回复，或者付费。
知悉上面条件后，可以点击左侧上面大概的位置 Slack connect 创建pro channel 试用即可，试用时长不太确定。
旧的工作区则正常使用。

**Comment by NoahAmethyst** [comment]
> 新的工作区现在被限制了，只能开启pro试用才能回复，或者付费。 知悉上面条件后，可以点击左侧上面大概的位置 Slack connect 创建pro channel 试用即可，试用时长不太确定。 旧的工作区则正常使用。

Oh shit

**Comment by NoahAmethyst** [comment]
> 新的工作区现在被限制了，只能开启pro试用才能回复，或者付费。 知悉上面条件后，可以点击左侧上面大概的位置 Slack connect 创建pro channel 试用即可，试用时长不太确定。 旧的工作区则正常使用。

感谢你的解答 :)
