### ISSUE TITLE
关于彻底解决注册时报signup_disabled

### ISSUE THREAD

**Issue by m-d-z-z** [bincooo/claude-api#17]
非常感谢大佬开此坑！

近期是发现用着用着就报账号readonly了，之后重新login报signup_disabled是因为邮箱被拉黑了？
观察了近期几次更新，貌似是从邮箱接码解决的？触发这个原因是因为上面说的邮箱后缀导致的嘛？
感觉可以把接码业务抽象成接口来方便后期无缝或自行实现此项功能？
还有recaptcha的验证码token有没有可能从他们的前端js里抓取？

希望能跟大佬讨论一下这些问题，之后我看一下能不能帮忙一起改进这个过程~

**Comment by bincooo** [comment]
readonly 是账号异常被锁了。signup_disabled 要么是一些后缀的邮箱被禁，要没就是ip被禁。不过今天认证再次加强了，需要手机号了
