### ISSUE TITLE
An API error occurred: missing_scope' 'Error: An API error occurred: missing_scope

### ISSUE THREAD

**Issue by c121914yu** [bincooo/claude-api#2]
An API error occurred: missing_scope' 'Error: An API error occurred: missing_scope
I have added permissions, but there is still this error

**Comment by bincooo** [comment]
You need to add the following permissions:
      channels:history, 
      channels:read, 
      channels:write, 
      groups:history, 
      groups:read, 
      groups:write,
      ​ chat:write, 
      im:history, 
      im:write, 
      mpim:history, 
      mpim:write

Do you click `Reinstall to Workspace` or  `Install to Workspace`  after adding?

**Comment by c121914yu** [comment]
yes.i success. thank

**Comment by c121914yu** [comment]
> You need to add the following permissions:
>       channels:history, 
>       channels:read, 
>       channels:write, 
>       groups:history, 
>       groups:read, 
>       groups:write,
>       ​ chat:write, 
>       im:history, 
>       im:write, 
>       mpim:history, 
>       mpim:write
> 
> Do you click `Reinstall to Workspace` or  `Install to Workspace`  after adding?

I saw the picture and thought I only needed to add 3 permissions.
