### ISSUE TITLE
这个的qps是多少呢？

### ISSUE THREAD

**Issue by lys623** [bincooo/claude-api#4]
我刚在测试，使用3个频道，然后1分钟发送4千个请求，发现一百多就被频控了。是否可以实现1分钟4千个请求的需求呢？

![image](https://github.com/bincooo/claude-api/assets/4364314/e514cfb1-ed6c-446e-aa15-af0c9acad600)

有一些会没有回复
![image](https://github.com/bincooo/claude-api/assets/4364314/25dd93a6-6e19-41e6-8f79-615c86c7681b)

**Comment by bincooo** [comment]
不太清楚，这应该是claude的自己的限流机制

**Comment by lys623** [comment]
> 不太清楚，这应该是claude的自己的限流机制 还有，一个会话内最好是顺序处理对话。多个对话同时处理是不行的

了解，不过我这边诉求是不用记录上下文，一问一答就可以

**Comment by lys623** [comment]
如何想实现1分钟4千个请求的需求，有方案吗？

**Comment by QingShan-123** [comment]
> 如何想实现1分钟4千个请求的需求，有方案吗？

限流很严重呀，我开了100个channel去聊天，有回复的也就二三十条。其余都是提示"_Claude is busy responding to other messages in this workspace. Please try again later._"

**Comment by bincooo** [comment]
https://api.slack.com/docs/rate-limits#tier_t5
